version: '3'

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  web:
    build: .
    env_file: .env
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && daphne athenian.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

volumes:
  postgres_data: